### PR TITLE
Revert "Upload image directly to HA instance"

### PR DESCRIPTION
**Pull request by WJDDesigns**
Reverts WJDDesigns/Ultra-Vehicle-Card#17

### CODE REVIEW

**Comment by ngocjohn** [comment]
Is there an issue with the code?

**Comment by WJDDesigns** [comment]
I am going to be full transparent, I am new to Github and I am learning. Is there a way to resubmit with the newest build and I will add it in? I looked at the code and saw a bunch of changes and I didn't want it to affect the newest build too much.

**Comment by WJDDesigns** [comment]
> Set up some compiler for the build... you'll have too many files...

Not sure what you mean. Should I delete this branch and have you resubmit?

**Comment by ngocjohn** [comment]
I tried to add a function for uploading images directly to HA.. but you push new commits so fast, so I'm already a lot of commits behind.. and I don't manage to put the changes together.  As a compiler I meant to use another plugin that combine multiple JavaScript files into a single file, often optimizing the code for faster loading. 
Now you have 3 files that you have to download and upload to the www, with the help of bundler you will compile them into 1 which will optimize the code by removing unnecessary characters like whitespace and comments, which leads to smaller file sizes.

Feel free to delete the branch, I'll pull the new codes from you and make a new PR. 😄 

https://github.com/user-attachments/assets/fcc2308d-b133-43f8-a033-f6e496e4a671

**Pull request merged**
