### PR TITLE
Installing Prettier, Husky, and lint-staged

### PR DESCRIPTION
**Pull request by timmaurice**
### For Developers

To get started with the project, follow these steps:

1. Install Bun:

   Bun is a fast all-in-one JavaScript runtime. You can install it by following the instructions on their [official website](https://bun.sh/).

2. Initial Setup:

   Once you have Bun installed, run the following command to install the necessary dependencies:

```
bun i
```

This command installs Prettier, Husky, and lint-staged, which are configured to automatically format your code when you commit changes in Git.

3. Automatic Code Formatting:

- Prettier: Ensures consistent code formatting across the project.
- Husky: Hooks into Git to run scripts on specific Git events (e.g., pre-commit).
- lint-staged: Runs linters on staged files in Git, ensuring only files related to your commit are checked.

4. Manual Code Formatting:

   If you need to format your code manually, you can do so by running:

   ```
   bun run format
   ```

   This will apply the project’s formatting rules to your codebase.

With these tools, your code will be automatically formatted according to the project’s standards every time you commit changes, helping maintain a clean and consistent codebase.

Please let me know what you think. 🙏

### CODE REVIEW

**Comment by WJDDesigns** [comment]
This might need to wait, I will focus on code cleanup and learning this after. This is a hobby of mine and a learn as you go so that might not be in my scope currently but will be something I can look at later. Trust me keeping things clean and tidy is a huge thing but for me this is still over my head.

**Comment by timmaurice** [comment]
Hi Wayne,

No problem at all! I completely understand that you’re focusing on code cleanup and learning at your own pace. Whenever you’re ready to dive into these tools, feel free to reach out. I’m more than happy to help and explain everything I did in detail.

Just a note, having these formatting tools in place becomes more crucial when multiple people are working on the repo, as it helps maintain consistency and avoids potential issues. But take your time—there’s no rush.

Looking forward to collaborating!

**Comment by WJDDesigns** [comment]
Do you have a discord? I just created a new one for my business with this card as a channel and I could add you in there. https://discord.gg/xKGN3SVg

**Comment by WJDDesigns** [comment]
I had added formatters and items for VS on save. Thanks for the suggestion!

**Pull request closed without merging**
